# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Home Page
tagline:             'This is where I start blogging. Stay tuned!'
description:         'I am a security enthusiast who is currently working as security engineer at Intuit. This blog post I will be using to write some tech blogs so that I can share my knowledge with the world and keep an archive for myself.'
url:                 https://tejas619.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Tejas Khairnar
  url:               https://twitter.com/khts123
  email:             tkhairna@asu.edu

# Custom vars
version:             1.0.0
